### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by unicomp21** [nats-io/nats.ws#135]
● Test suite failed to run

    ReferenceError: TextEncoder is not defined

      2 | import { render, screen } from '@testing-library/react';
      3 | import App from './App';
    > 4 | import {connect} from "nats.ws";
        | ^
      5 |
      6 | test('renders learn react link', () => {
      7 |   render(<App />);

      at Object.<anonymous> (node_modules/nats.ws/nats-base-client/encoders.ts:18:23)
      at Object.<anonymous> (node_modules/nats.ws/nats-base-client/databuffer.ts:16:1)
      at Object.<anonymous> (node_modules/nats.ws/nats-base-client/util.ts:16:1)
      at Object.<anonymous> (node_modules/nats.ws/nats-base-client/nats.ts:16:1)
      at Object.<anonymous> (node_modules/nats.ws/nats-base-client/internal_mod.ts:1:1)
      at Object.<anonymous> (node_modules/nats.ws/nats-base-client/mod.ts:1:1)
      at Object.<anonymous> (node_modules/nats.ws/wst/mod.ts:15:1)
      at Object.<anonymous> (node_modules/nats.ws/cjs/nats.js:17:18)
      at Object.<anonymous> (src/App.test.tsx:4:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:173:3)

**Comment by aricart** [comment]
Could you verify with this:

https://github.com/aricart/natsws-react-fixture

**Comment by unicomp21** [comment]
Getting a new error now:

App.tsx:62 starting: /index.js
nats.js:8268 > INFO {"server_id":"NDI4FJM42FXZD6NVD5C3F2NSIR3256A6L6DOJMSKYYSFCSJAPW3C4KLA","server_name":"NDI4FJM42FXZD6NVD5C3F2NSIR3256A6L6DOJMSKYYSFCSJAPW3C4KLA","version":"2.7.3-beta.2","proto":1,"git_commit":"58806c12","go":"go1.17.7","host":"0.0.0.0","port":4222,"headers":true,"max_payload":1048576,"client_id":19,"client_ip":"172.17.0.1"} ␍␊
nats.js:8291 < CONNECT {"no_responders":true,"protocol":1,"verbose":false,"pedantic":false,"lang":"nats.ws","version":"1.7.2","headers":true}␍␊
nats.js:8291 < PING␍␊
nats.js:8268 > PONG␍␊
nats.js:8291 < SUB _INBOX.66JA4SZZBAMNR84LB1GNG9.* 1␍␊PUB $JS.API.INFO _INBOX.66JA4SZZBAMNR84LB1GNG9.66JA4SZZBAMNR84LB1GN7R 0␍␊␍␊
nats.js:8268 > HMSG _INBOX.66JA4SZZBAMNR84LB1GNG9.66JA4SZZBAMNR84LB1GN7R 1 16 16␍␊NATS/1.0 503␍␊␍␊␍␊
NatsError: 503
    at Function.errorForCode (http://localhost:3000/static/js/bundle.js:42236:12)
    at isRequestError (http://localhost:3000/static/js/bundle.js:43812:26)
    at SubscriptionImpl.callback (http://localhost:3000/static/js/bundle.js:45838:19)
    at ProtocolHandler.processMsg (http://localhost:3000/static/js/bundle.js:46175:11)
    at ProtocolHandler.push (http://localhost:3000/static/js/bundle.js:46295:16)
    at Parser.parse (http://localhost:3000/static/js/bundle.js:45142:29)
    at http://localhost:3000/static/js/bundle.js:46034:25

Error
    at new Request (http://localhost:3000/static/js/bundle.js:43434:16)
    at NatsConnectionImpl.request (http://localhost:3000/static/js/bundle.js:50659:17)
    at JetStreamManagerImpl._request (http://localhost:3000/static/js/bundle.js:43163:29)
    at JetStreamManagerImpl.getAccountInfo (http://localhost:3000/static/js/bundle.js:49028:26)
    at NatsConnectionImpl.jetstreamManager (http://localhost:3000/static/js/bundle.js:50737:17)
    at main (http://localhost:3000/static/js/bundle.js:139:36)
Promise.catch (async)
./src/App.tsx @ App.tsx:66
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:61
./src/index.tsx @ App.tsx:66
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:7
(anonymous) @ startup:7
nats.js:8268 > PING␍␊
nats.js:8291 < PONG␍␊
nats.js:8268 > PING␍␊
nats.js:8291 < PONG␍␊
nats.js:8291 < PING␍␊
nats.js:8268 > PONG␍␊
nats.js:8291 < PING␍␊
nats.js:8268 > PONG␍␊
nats.js:8291 < PING␍␊
nats.js:8268 > PONG␍␊
nats.js:8291 < PING␍␊
nats.js:8268 > PONG␍␊
nats.js:8291 < PING␍␊
nats.js:8268 > PONG␍␊
nats.js:8291 < PING␍␊
nats.js:8268 > PONG␍␊
nats.js:8291 < PING␍␊
nats.js:8268 > PONG␍␊

**Comment by aricart** [comment]
looks like you are connected. the 503 is in response to the jetstream request - you can check the server on that.

**Comment by unicomp21** [comment]
I see a 503 in the logs, but am unsure how to decipher what it means?

**Comment by unicomp21** [comment]
[1] 2022/02/19 17:58:24.606607 [DBG] 172.17.0.1:62520 - wid:4 - Client connection created
[1] 2022/02/19 17:58:24.608232 [TRC] SYSTEM - <<- [PUB $SYS.SERVER.ACCOUNT.$G.CONNS  425]
[1] 2022/02/19 17:58:24.608395 [TRC] SYSTEM - <<- MSG_PAYLOAD: ["{\"type\":\"io.nats.server.advisory.v1.account_connections\",\"id\":\"XH4v7aF6bON0Ciyu8Y0HQn\",\"timestamp\":\"2022-02-19T17:58:24.6065537Z\",\"server\":{\"name\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"host\":\"0.0.0.0\",\"id\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"ver\":\"2.7.3-beta.2\",\"seq\":13,\"jetstream\":false,\"time\":\"2022-02-19T17:58:24.6081473Z\"},\"acc\":\"$G\",\"conns\":1,\"leafnodes\":0,\"total_conns\":1}"]
[1] 2022/02/19 17:58:24.608503 [TRC] SYSTEM - <<- [PUB $SYS.ACCOUNT.$G.SERVER.CONNS  425]
[1] 2022/02/19 17:58:24.608553 [TRC] SYSTEM - <<- MSG_PAYLOAD: ["{\"type\":\"io.nats.server.advisory.v1.account_connections\",\"id\":\"XH4v7aF6bON0Ciyu8Y0HQn\",\"timestamp\":\"2022-02-19T17:58:24.6065537Z\",\"server\":{\"name\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"host\":\"0.0.0.0\",\"id\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"ver\":\"2.7.3-beta.2\",\"seq\":14,\"jetstream\":false,\"time\":\"2022-02-19T17:58:24.6084654Z\"},\"acc\":\"$G\",\"conns\":1,\"leafnodes\":0,\"total_conns\":1}"]
[1] 2022/02/19 17:58:24.628546 [TRC] 172.17.0.1:62520 - wid:4 - <<- [CONNECT {"no_responders":true,"protocol":1,"verbose":false,"pedantic":false,"lang":"nats.ws","version":"1.7.2","headers":true}]
[1] 2022/02/19 17:58:24.629022 [TRC] 172.17.0.1:62520 - wid:4 - "v1.7.2:nats.ws" - <<- [PING]
[1] 2022/02/19 17:58:24.629060 [TRC] 172.17.0.1:62520 - wid:4 - "v1.7.2:nats.ws" - ->> [PONG]
[1] 2022/02/19 17:58:24.638764 [TRC] 172.17.0.1:62520 - wid:4 - "v1.7.2:nats.ws" - <<- [SUB test 1]
[1] 2022/02/19 17:58:24.638860 [TRC] 172.17.0.1:62520 - wid:4 - "v1.7.2:nats.ws" - <<- [PUB test 12]
[1] 2022/02/19 17:58:24.638884 [TRC] 172.17.0.1:62520 - wid:4 - "v1.7.2:nats.ws" - <<- MSG_PAYLOAD: ["test message"]
[1] 2022/02/19 17:58:24.638906 [TRC] 172.17.0.1:62520 - wid:4 - "v1.7.2:nats.ws" - ->> [MSG test 1 12]
[1] 2022/02/19 17:58:24.638961 [TRC] 172.17.0.1:62520 - wid:4 - "v1.7.2:nats.ws" - <<- [SUB _INBOX.DDOIIDNIQKQJ10PSJCEAID.* 2]
[1] 2022/02/19 17:58:24.639050 [TRC] 172.17.0.1:62520 - wid:4 - "v1.7.2:nats.ws" - <<- [PUB $JS.API.INFO _INBOX.DDOIIDNIQKQJ10PSJCEAID.DDOIIDNIQKQJ10PSJCEAGV 0]
[1] 2022/02/19 17:58:24.639068 [TRC] 172.17.0.1:62520 - wid:4 - "v1.7.2:nats.ws" - <<- MSG_PAYLOAD: [""]
[1] 2022/02/19 17:58:25.851287 [TRC] SYSTEM - <<- [PUB $SYS.SERVER.ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A.STATSZ  504]
[1] 2022/02/19 17:58:25.851738 [TRC] SYSTEM - <<- MSG_PAYLOAD: ["{\"server\":{\"name\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"host\":\"0.0.0.0\",\"id\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"ver\":\"2.7.3-beta.2\",\"seq\":15,\"jetstream\":false,\"time\":\"2022-02-19T17:58:25.8511834Z\"},\"statsz\":{\"start\":\"2022-02-19T17:58:10.075495Z\",\"mem\":10547200,\"cores\":4,\"cpu\":1,\"connections\":1,\"total_connections\":1,\"active_accounts\":2,\"subscriptions\":40,\"sent\":{\"msgs\":1,\"bytes\":12},\"received\":{\"msgs\":2,\"bytes\":12},\"slow_consumers\":0,\"active_servers\":1}}"]
[1] 2022/02/19 17:58:26.828681 [DBG] 172.17.0.1:62520 - wid:4 - "v1.7.2:nats.ws" - Client Ping Timer
[1] 2022/02/19 17:58:26.829150 [TRC] 172.17.0.1:62520 - wid:4 - "v1.7.2:nats.ws" - ->> [PING]
[1] 2022/02/19 17:58:26.837016 [TRC] 172.17.0.1:62520 - wid:4 - "v1.7.2:nats.ws" - <<- [PONG]
[1] 2022/02/19 17:58:41.820227 [TRC] SYSTEM - <<- [PUB $SYS.SERVER.ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A.STATSZ  504]
[1] 2022/02/19 17:58:41.820393 [TRC] SYSTEM - <<- MSG_PAYLOAD: ["{\"server\":{\"name\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"host\":\"0.0.0.0\",\"id\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"ver\":\"2.7.3-beta.2\",\"seq\":16,\"jetstream\":false,\"time\":\"2022-02-19T17:58:41.8197041Z\"},\"statsz\":{\"start\":\"2022-02-19T17:58:10.075495Z\",\"mem\":10547200,\"cores\":4,\"cpu\":0,\"connections\":1,\"total_connections\":1,\"active_accounts\":2,\"subscriptions\":40,\"sent\":{\"msgs\":1,\"bytes\":12},\"received\":{\"msgs\":2,\"bytes\":12},\"slow_consumers\":0,\"active_servers\":1}}"]
[1] 2022/02/19 17:58:54.577747 [TRC] SYSTEM - <<- [PUB $SYS.SERVER.ACCOUNT.$G.CONNS  425]
[1] 2022/02/19 17:58:54.578267 [TRC] SYSTEM - <<- MSG_PAYLOAD: ["{\"type\":\"io.nats.server.advisory.v1.account_connections\",\"id\":\"XH4v7aF6bON0Ciyu8Y0HZD\",\"timestamp\":\"2022-02-19T17:58:54.5774481Z\",\"server\":{\"name\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"host\":\"0.0.0.0\",\"id\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"ver\":\"2.7.3-beta.2\",\"seq\":17,\"jetstream\":false,\"time\":\"2022-02-19T17:58:54.5776295Z\"},\"acc\":\"$G\",\"conns\":1,\"leafnodes\":0,\"total_conns\":1}"]
[1] 2022/02/19 17:58:54.578634 [TRC] SYSTEM - <<- [PUB $SYS.ACCOUNT.$G.SERVER.CONNS  425]
[1] 2022/02/19 17:58:54.579676 [TRC] SYSTEM - <<- MSG_PAYLOAD: ["{\"type\":\"io.nats.server.advisory.v1.account_connections\",\"id\":\"XH4v7aF6bON0Ciyu8Y0HZD\",\"timestamp\":\"2022-02-19T17:58:54.5774481Z\",\"server\":{\"name\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"host\":\"0.0.0.0\",\"id\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"ver\":\"2.7.3-beta.2\",\"seq\":18,\"jetstream\":false,\"time\":\"2022-02-19T17:58:54.5784527Z\"},\"acc\":\"$G\",\"conns\":1,\"leafnodes\":0,\"total_conns\":1}"]
[1] 2022/02/19 17:59:11.785152 [TRC] SYSTEM - <<- [PUB $SYS.SERVER.ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A.STATSZ  504]
[1] 2022/02/19 17:59:11.785331 [TRC] SYSTEM - <<- MSG_PAYLOAD: ["{\"server\":{\"name\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"host\":\"0.0.0.0\",\"id\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"ver\":\"2.7.3-beta.2\",\"seq\":19,\"jetstream\":false,\"time\":\"2022-02-19T17:59:11.7850541Z\"},\"statsz\":{\"start\":\"2022-02-19T17:58:10.075495Z\",\"mem\":10547200,\"cores\":4,\"cpu\":0,\"connections\":1,\"total_connections\":1,\"active_accounts\":2,\"subscriptions\":40,\"sent\":{\"msgs\":1,\"bytes\":12},\"received\":{\"msgs\":2,\"bytes\":12},\"slow_consumers\":0,\"active_servers\":1}}"]
[1] 2022/02/19 17:59:24.549254 [TRC] SYSTEM - <<- [PUB $SYS.SERVER.ACCOUNT.$G.CONNS  425]
[1] 2022/02/19 17:59:24.549515 [TRC] SYSTEM - <<- MSG_PAYLOAD: ["{\"type\":\"io.nats.server.advisory.v1.account_connections\",\"id\":\"XH4v7aF6bON0Ciyu8Y0HdQ\",\"timestamp\":\"2022-02-19T17:59:24.5465908Z\",\"server\":{\"name\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"host\":\"0.0.0.0\",\"id\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"ver\":\"2.7.3-beta.2\",\"seq\":20,\"jetstream\":false,\"time\":\"2022-02-19T17:59:24.5466842Z\"},\"acc\":\"$G\",\"conns\":1,\"leafnodes\":0,\"total_conns\":1}"]
[1] 2022/02/19 17:59:24.549945 [TRC] SYSTEM - <<- [PUB $SYS.ACCOUNT.$G.SERVER.CONNS  425]
[1] 2022/02/19 17:59:24.551576 [TRC] SYSTEM - <<- MSG_PAYLOAD: ["{\"type\":\"io.nats.server.advisory.v1.account_connections\",\"id\":\"XH4v7aF6bON0Ciyu8Y0HdQ\",\"timestamp\":\"2022-02-19T17:59:24.5465908Z\",\"server\":{\"name\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"host\":\"0.0.0.0\",\"id\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"ver\":\"2.7.3-beta.2\",\"seq\":21,\"jetstream\":false,\"time\":\"2022-02-19T17:59:24.5496032Z\"},\"acc\":\"$G\",\"conns\":1,\"leafnodes\":0,\"total_conns\":1}"]
[1] 2022/02/19 17:59:41.750246 [TRC] SYSTEM - <<- [PUB $SYS.SERVER.ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A.STATSZ  503]
[1] 2022/02/19 17:59:41.750370 [TRC] SYSTEM - <<- MSG_PAYLOAD: ["{\"server\":{\"name\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"host\":\"0.0.0.0\",\"id\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"ver\":\"2.7.3-beta.2\",\"seq\":22,\"jetstream\":false,\"time\":\"2022-02-19T17:59:41.750159Z\"},\"statsz\":{\"start\":\"2022-02-19T17:58:10.075495Z\",\"mem\":10547200,\"cores\":4,\"cpu\":0,\"connections\":1,\"total_connections\":1,\"active_accounts\":2,\"subscriptions\":40,\"sent\":{\"msgs\":1,\"bytes\":12},\"received\":{\"msgs\":2,\"bytes\":12},\"slow_consumers\":0,\"active_servers\":1}}"]
[1] 2022/02/19 17:59:54.512288 [TRC] SYSTEM - <<- [PUB $SYS.SERVER.ACCOUNT.$G.CONNS  425]
[1] 2022/02/19 17:59:54.512373 [TRC] SYSTEM - <<- MSG_PAYLOAD: ["{\"type\":\"io.nats.server.advisory.v1.account_connections\",\"id\":\"XH4v7aF6bON0Ciyu8Y0Hhd\",\"timestamp\":\"2022-02-19T17:59:54.5121022Z\",\"server\":{\"name\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"host\":\"0.0.0.0\",\"id\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"ver\":\"2.7.3-beta.2\",\"seq\":23,\"jetstream\":false,\"time\":\"2022-02-19T17:59:54.5121852Z\"},\"acc\":\"$G\",\"conns\":1,\"leafnodes\":0,\"total_conns\":1}"]
[1] 2022/02/19 17:59:54.512906 [TRC] SYSTEM - <<- [PUB $SYS.ACCOUNT.$G.SERVER.CONNS  425]
[1] 2022/02/19 17:59:54.513087 [TRC] SYSTEM - <<- MSG_PAYLOAD: ["{\"type\":\"io.nats.server.advisory.v1.account_connections\",\"id\":\"XH4v7aF6bON0Ciyu8Y0Hhd\",\"timestamp\":\"2022-02-19T17:59:54.5121022Z\",\"server\":{\"name\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"host\":\"0.0.0.0\",\"id\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"ver\":\"2.7.3-beta.2\",\"seq\":24,\"jetstream\":false,\"time\":\"2022-02-19T17:59:54.5128457Z\"},\"acc\":\"$G\",\"conns\":1,\"leafnodes\":0,\"total_conns\":1}"]
[1] 2022/02/19 18:00:11.716224 [TRC] SYSTEM - <<- [PUB $SYS.SERVER.ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A.STATSZ  504]
[1] 2022/02/19 18:00:11.716496 [TRC] SYSTEM - <<- MSG_PAYLOAD: ["{\"server\":{\"name\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"host\":\"0.0.0.0\",\"id\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"ver\":\"2.7.3-beta.2\",\"seq\":25,\"jetstream\":false,\"time\":\"2022-02-19T18:00:11.7161045Z\"},\"statsz\":{\"start\":\"2022-02-19T17:58:10.075495Z\",\"mem\":10739712,\"cores\":4,\"cpu\":0,\"connections\":1,\"total_connections\":1,\"active_accounts\":2,\"subscriptions\":40,\"sent\":{\"msgs\":1,\"bytes\":12},\"received\":{\"msgs\":2,\"bytes\":12},\"slow_consumers\":0,\"active_servers\":1}}"]
[1] 2022/02/19 18:00:24.477581 [TRC] SYSTEM - <<- [PUB $SYS.SERVER.ACCOUNT.$G.CONNS  425]
[1] 2022/02/19 18:00:24.477961 [TRC] SYSTEM - <<- MSG_PAYLOAD: ["{\"type\":\"io.nats.server.advisory.v1.account_connections\",\"id\":\"XH4v7aF6bON0Ciyu8Y0Hlq\",\"timestamp\":\"2022-02-19T18:00:24.4772197Z\",\"server\":{\"name\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"host\":\"0.0.0.0\",\"id\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"ver\":\"2.7.3-beta.2\",\"seq\":26,\"jetstream\":false,\"time\":\"2022-02-19T18:00:24.4773899Z\"},\"acc\":\"$G\",\"conns\":1,\"leafnodes\":0,\"total_conns\":1}"]
[1] 2022/02/19 18:00:24.478326 [TRC] SYSTEM - <<- [PUB $SYS.ACCOUNT.$G.SERVER.CONNS  425]
[1] 2022/02/19 18:00:24.478913 [TRC] SYSTEM - <<- MSG_PAYLOAD: ["{\"type\":\"io.nats.server.advisory.v1.account_connections\",\"id\":\"XH4v7aF6bON0Ciyu8Y0Hlq\",\"timestamp\":\"2022-02-19T18:00:24.4772197Z\",\"server\":{\"name\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"host\":\"0.0.0.0\",\"id\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"ver\":\"2.7.3-beta.2\",\"seq\":27,\"jetstream\":false,\"time\":\"2022-02-19T18:00:24.4782384Z\"},\"acc\":\"$G\",\"conns\":1,\"leafnodes\":0,\"total_conns\":1}"]
[1] 2022/02/19 18:00:24.648478 [TRC] 172.17.0.1:62520 - wid:4 - "v1.7.2:nats.ws" - <<- [PING]
[1] 2022/02/19 18:00:24.648568 [TRC] 172.17.0.1:62520 - wid:4 - "v1.7.2:nats.ws" - ->> [PONG]
[1] 2022/02/19 18:00:26.688902 [DBG] 172.17.0.1:62520 - wid:4 - "v1.7.2:nats.ws" - Client Ping Timer
[1] 2022/02/19 18:00:26.690102 [DBG] 172.17.0.1:62520 - wid:4 - "v1.7.2:nats.ws" - Delaying PING due to remote ping 2s ago
[1] 2022/02/19 18:00:41.685053 [TRC] SYSTEM - <<- [PUB $SYS.SERVER.ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A.STATSZ  504]
[1] 2022/02/19 18:00:41.685223 [TRC] SYSTEM - <<- MSG_PAYLOAD: ["{\"server\":{\"name\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"host\":\"0.0.0.0\",\"id\":\"ND4RDEXMF2A4GVXCYHHSYHP5UNGVXHQQUHSWZ3BWJPA7Y56NXQXLXE2A\",\"ver\":\"2.7.3-beta.2\",\"seq\":28,\"jetstream\":false,\"time\":\"2022-02-19T18:00:41.6849571Z\"},\"statsz\":{\"start\":\"2022-02-19T17:58:10.075495Z\",\"mem\":11575296,\"cores\":4,\"cpu\":0,\"connections\":1,\"total_connections\":1,\"active_accounts\":2,\"subscriptions\":40,\"sent\":{\"msgs\":1,\"bytes\":12},\"received\":{\"msgs\":2,\"bytes\":12},\"slow_consumers\":0,\"active_servers\":1}}"]

**Comment by unicomp21** [comment]
</stupidme> got distracted and forgot -js in my docker script, good2go.  Thanks @aricart !
