### ISSUE TITLE
Possible `crypto` lib issue when running in NodeJS (object store)

### ISSUE THREAD

**Issue by jmordica** [nats-io/nats.ws#162]
Using NodeJS v16.16 and using ESM, we are running into a crypto related issue when running the following:

```js
// Initialize the object store
this.os = await this.js.views.os(this.streamName, { storage: StorageType.File });

// Which produces:

ReferenceError: crypto is not defined
at Function.<anonymous> (/myproj/node_modules/nats.ws/nats-base-client/objectstore.ts:667:5)
```

So we tried Shim'ing the crypto module by adding:

```js
// Initialize the object store
globalThis.crypto = require("crypto");
this.os = await this.js.views.os(this.streamName, { storage: StorageType.File });

// Which produces:

Error: objectstore: unable to calculate hashes - crypto.subtle.digest with sha256 support is required
at Function.<anonymous> (/myproj/node_modules/nats.ws/nats-base-client/objectstore.ts:669:9)
```

Any thoughts here?

Thanks!

**Comment by aricart** [comment]
Try this:

```
import {default as crypto} from "crypto";
console.log(typeof crypto, crypto)
globalThis.crypto = crypto.webcrypto;

const nc = await connect({ servers: ["ws://localhost:80"] });
console.log("connected");

const js = nc.jetstream();
await js.views.os("OS");

await nc.close();
```

**Comment by aricart** [comment]
This flew from my radar - the test already had a sample
https://github.com/nats-io/nats.ws/blob/main/test/jetstream.js#L346
