### ISSUE TITLE
Empty/Null message processing with JSON payloads

### ISSUE THREAD

**Issue by gbintz** [nats-io/nats.ws#24]
Receipt of a empty/null message when configured with JSON payloads causes the following error:

**NatsError: Bad JSON**
`    at Function.errorForCode (webpack-internal:///./node_modules/nats.ws/nats.js:1:2803)
    at T.fill (webpack-internal:///./node_modules/nats.ws/nats.js:1:13659)
    at I.processInbound (webpack-internal:///./node_modules/nats.ws/nats.js:1:15991)
    at I.messageHandler (webpack-internal:///./node_modules/nats.ws/nats.js:1:18206)
    at WebSocket.a.stream.onmessage (webpack-internal:///./node_modules/nats.ws/nats.js:8:24784)`

Recommend adding a special case when empty/null message (0 length), set msg data to an empty object ({}) in protocol.ts's fill method. 

The use case is an empty command or event without a payload. This should be a valid use case when the subject provides all necessary context.

**Comment by aricart** [comment]
If the client is set to JSON payloads all the interactions from that client must be JSON. This is a common behavior for javascript clients. With that said, I want to change this behavior as well because I have run into it several times.

I believe the client shouldn't be tied to a particular encoding. This has a subtle side effect on the APIs. The publishing and data signature would take payloads as UInt8Arrays. Which means that client will be responsible for decoding/encoding. I believe this would be the correct strategy.

Currently, I have v2 branches for nats.js, nats.ts (async API), and I am working on the Deno client, which is going to create a few changes on the internals of the nats.ws, so I will address this.

**Comment by aricart** [comment]
Also - the reason why we cannot do this is because an empty JSON message could be null, empty string, number, string or object. JSON has specific encoding for all these, so the library cannot really make an assumption here that will be right for everyone.
